### ISSUE TITLE
Server returning json blob containing key named "errors", code looks for key named "error"

### ISSUE THREAD

**Issue by nehresma** [gocardless/gocardless-python#25]
In the sandbox, I created a test pre-authorization with a monthly max of 5000 GBP.  I ran several tests through just fine, but suddenly started getting errors back.

Looking into it, I see that the pre-auth limit has been reached on my test, but the error being raised is a KeyError on an 'id' field.  This is because the server returns a json blob that looks like:

    '{"errors":{"pre_authorization":["maximum amount exceeded for the period 2015-04-20 00:00:00 UTC..2015-05-19 23:59:59 UTC (GBP725.0 requested, only GBP600.0 remaining)."]}}'

The code in client.py looks for a key named "error", which doesn't exist.  So it doesn't raise the ClientError about exceeding the limit:

        if type(response) == dict and "error" in response.keys():
            raise ClientError("Error calling api, message was {0}".format(
                response["error"]))

https://github.com/gocardless/gocardless-python/blob/master/gocardless/client.py#L119

Since this is in the Client class, this problem probably isn't isolated to this particular error.

**Comment by nehresma** [comment]
I suspect that this was a change on the server side at some point recently and the change didn't make it into the wrapper.

**Comment by pegler** [comment]
We have also seen this error many times.  We first saw it on Nov 24 2014, so it's not new.  

The "confirm resource" API call does return a key named "error", while it looks like creating a bill uses the key "errors".  So it looks like the wrapper needs to handle both of those.

**Comment by nehresma** [comment]
Thanks for the heads up.  I'll update the PR to handle both.

**Comment by nehresma** [comment]
It looks like the Ruby client may also suffer from a similar issue:
https://github.com/gocardless/gocardless-ruby/blob/master/lib/gocardless/errors.rb#L15

**Comment by hmarr** [comment]
Sorry about this - just had a look into it now. It turns out we use `errors` in most places, but there are a few cases in which `error` is used instead (404s, 500s).

We'd like to make this consistent, and as you get an array of errors back, we're going to add support for `errors` everywhere (though we'll maintain support `error` in a few places so we don't break backwards compatibility).

As a result, we should update the libraries to look for `errors` rather than `error`. @nehresma - are you happy to update your PR to reflect that? Should be a small change!

**Comment by hmarr** [comment]
Actually, scratch that. The types of `error` and `errors` are different (the former is an array, and the latter is a dictionary), so rather than introducing a potentially breaking change, we'll just handle both cases in the client lib. Let's move this to #26.
